chunk_overlap: 20
chunk_size: 1024
controller_url: https://nuclio-gator-demo-controller.default-tenant.svc.cluster.local:8080
controller_username: guest
default_llm:
  class_name: langchain_openai.ChatOpenAI
  model_name: gpt-4o-mini
  temperature: 0
default_vector_store:
  class_name: chroma
  collection_name: default
  persist_directory: /tmp/chromadb/chroma
deployment_url: http://0.0.0.0:8000
embeddings:
  class_name: huggingface
  model_name: all-MiniLM-L6-v2
log_level: INFO
project_name: gator-demo
verbose: true
workflows_kwargs: {}